server:
  port: 9999
spring:
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/webapp
      additional-exclude: static/**, templates/**
    livereload:
      enabled: true
  application:
    name: member_post
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://np.eeerrorcode.com:3306/post
    url: jdbc:log4jdbc:mariadb://np.eeerrorcode.com:3306/post
    username: sample
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-request-size:
        50MB
      file-size-threshold:
        10MB
      location: c:/upload
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.eeerrorcode.member_post.vo
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  swagger-ui:
    path: /swag

upload:
  path: c:/upload