server:
  port: 9999
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  application:
    name: member_post
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://np.eeerrorcode.com:3306/post
    url: jdbc:log4jdbc:mariadb://np.eeerrorcode.com:3306/post
    username: sample
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.eeerrorcode.member_post.vo
  configuration:
    map-underscore-to-camel-case: true